name: CI Workflow

on: [push, pull_request]

permissions:
  contents: read

env:
  SOLUTION_FILE_PATH: 'Apocalypse'

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        build-configuration: [Debug, Release]
    steps:
    - name: Clone Git Repository
      uses: actions/checkout@v4
      with: 
        repository: 'sebimih13/Proiect-MDS' # TODO: change
        submodules: true
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64
    - name: Setup
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: generate_project.bat
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild ${{env.SOLUTION_FILE_PATH}} /m /p:Configuration=${{matrix.build-configuration}}

