name: CI Workflow

on: [push]

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        config: [debug, release]
        platform: [x64]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: dir
      run: dir
